### ISSUE TITLE
Detector processor must first be set with setProcessor in order to receive detection results.

### ISSUE THREAD

**Issue by TMIndust** [nisrulz/qreader#11]
Hi,
tried to use googles vision api directly but the dectector was for some reason always "not operational" and now I have the same problem with your API and a modified version of your example app.
Log gets continously spammed with the following error message:

> 05-27 00:52:51.956 30999-709/evco.world.projects.de.evco E/CameraSource: Exception thrown from receiver.
>                                                                                  java.lang.IllegalStateException: Detector processor must first be set with setProcessor in order to receive detection results.
>                                                                                      at com.google.android.gms.vision.Detector.receiveFrame(Unknown Source)
>                                                                                      at com.google.android.gms.vision.CameraSource$zzb.run(Unknown Source)
>                                                                                      at java.lang.Thread.run(Thread.java:818)

Is it my device or...?
Code (little bit different from your example code):
```
@Override
    protected void onStart() {
        super.onStart();
        setContentView(R.layout.camera);

        hsCodes = new HashSet<String>();

        codepreview = (TextView)findViewById(R.id.codepreview);
        cameraView = (SurfaceView)findViewById(R.id.cameraView);

        qrEader = new QREader.Builder(this, cameraView, new QRDataListener() {
            @Override public void onDetected(final String data) {
                final String code = format( data );
                hsCodes.add(code);
                codepreview.post( new Runnable() {
                    @Override
                    public void run() {
                        codepreview.setText(code);
                    }
                });
            }
        }).build();
        qrEader.init();
    }

    @Override
    protected void onResume() {
        super.onResume();

        qrEader.start();
    }

    @Override
    protected void onPause() {
        super.onPause();

        qrEader.stop();
    }
```

**Comment by nisrulz** [comment]
@TMIndust Can you confirm that you have the same problem with the sample app too ?

**Comment by TMIndust** [comment]
Yes, same problem with the samle app, however as it stands right now there seems to be a bug in Googles Vision API, see
https://developers.google.com/android/guides/releases#may_2016_-_v90
from 5 days ago.
> A service required by Mobile Vision is now disabled due to a serious bug in that service.
> This will prevent users who have not already used face or barcode detection from using those features.
> We do not recommend adding new Mobile Vision features to your app until this issue is fixed.
> For apps that already use Mobile Vision features, check FaceDetector.isOperational() or BarcodeDetector.isOperational() to confirm detector readiness before using the face or barcode detector.
So it is probably not directly related with your library.

Thanks
