### ISSUE TITLE
Unable to initiate  QREader

### ISSUE THREAD

**Issue by amugox** [nisrulz/qreader#16]
I am getting below error wnen i call:  qrEader.init();

"java.lang.NoSuchMethodError: No static method zzC(Ljava/lang/Object;)Lcom/google/android/gms/dynamic/zzd; in class Lcom/google/android/gms/dynamic/zze; or its super classes (declaration of 'com.google.android.gms.dynamic.zze'"

**Comment by nisrulz** [comment]
@amugox can you please list the version of library and android you are using. 

Also provide device details and more logcat information for me to debug this properly.

**Comment by tijee** [comment]
I got the same error, you need to declare compile `'com.google.android.gms:play-services-vision:x.x.x'` in your `build.gradle`.

**Comment by nisrulz** [comment]
@tijee : Its already mentioned [here]( https://github.com/nisrulz/qreader/blob/master/library/build.gradle#L43) . I still have to replicate this issue, OP has not responded about this but if you are getting the same , then please provide me more details to replicate this issue and hence provide a solution asap.

**Comment by tijee** [comment]
No more details to give, this is actually not an issue. I just forgot to declare the play services dependency, and I guess @amugox did the same.

**Comment by nisrulz** [comment]
Closing as cannot replicate.
