### ISSUE TITLE
Stop and release camera

### ISSUE THREAD

**Issue by farruxx** [nisrulz/qreader#3]
how to release camera onPause or when the job is done?

**Comment by LeoUnglaub** [comment]
Hey,
i have to agree it would be very nice to have a stop method as well. That way you can stop the camera if you got the result you wanted. 

Thanks and greetings
Leo

**Comment by nisrulz** [comment]
Fixed in the latest release v1.0.3 , included functions to allow for `stop` and `releaseAndCleanup` when using QREader.
