### ISSUE TITLE
how can i use button in recyclerview??

### ISSUE THREAD

**Issue by wlchfl5358** [nisrulz/qreader#31]
i tried setOnClickListener in onBindViewHolder and ItemViewHolder...
but it happened nothing when i clicked.
should i use different way to set button in a row in recyclerView?
may i see some example?
even i tried in activty not adapter, it shows same.
and how can i change drag clickevent recyclerview to imageview or button?
thank you.

**Comment by nisrulz** [comment]
How is this related to QREader, Please explain.
