### ISSUE TITLE
Camera Preview Lagging

### ISSUE THREAD

**Issue by Wockito** [nisrulz/qreader#32]
I just followed the implementation as told in the wiki. The camera preview lags a lot on my Moto g 3rd Gen phone. Can something be done to smooth it out ?

**Comment by nisrulz** [comment]
@Wockito I will look into it. Meanwhile if you come up with some solution , do consider sending a PR.

**Comment by nisrulz** [comment]
Closing as issue is outdated. Please open a new issue if the issue still persists.
