### ISSUE TITLE
OnDetectMethodCall Multiple times

### ISSUE THREAD

**Issue by maltidevnani** [nisrulz/qreader#44]
I want to move from on activity to another on detecting the qrcode.But when i navigate from current activity to another activity its not happening and the detection keeps going on.It works fine if i move back to the parent (the activity which call the qrcode activity) on activity result.But i dont want to go for on activity result.

**Comment by nisrulz** [comment]
@maltidevnani I do not quite understand your issue. Could you explain a bit more clearly?

**Comment by nisrulz** [comment]
Closing as issue is outdated. Please open a new issue if the issue still persists.
