### ISSUE TITLE
Flash feature

### ISSUE THREAD

**Issue by RawanHamad** [nisrulz/qreader#57]
**Flash feature in develop branch to be fixed?**

In the develop branch , you can turn flash on and off , but after you scan anything this feature stops, and doesn't function properly.

**Comment by nisrulz** [comment]
It is not released yet. I am not finding time to sit down and make the fix. If you happen to get the time and would like to contribute then please open a PR. There is no set timeline for the resolution. It all depends when I can get time to fix this.

**Comment by nisrulz** [comment]
Closing as issue is outdated. Please open a new issue if the issue still persists.
