### ISSUE TITLE
Need Design Logo/Icon/Favicon

### ISSUE THREAD

**Issue by gcarlosr** [nisrulz/qreader#61]
Hi, how are you brother, I am a graphic designer I make contributions to open source applications. I have seen that you have an excellent app, but it lacks an icon that represents it and at the same time it can be shown in the favicon of the web (http://nisrulz.github.io/qreader). If you want I can make a contribution designing an attractive logo and that represents the app. Let me know your concerns and in advance thanks and apologies for opening this issue to consult.

**Comment by nisrulz** [comment]
This repo is not looking for this kind of contribution for now. I appreciate your offer though. Thank you.
