### ISSUE TITLE
OpenGLRenderer: endAllStagingAnimators on 0x55a2950170 (RippleDrawable) with handle 0x55a2661e30

### ISSUE THREAD

**Issue by pkylechu** [nisrulz/qreader#62]
**Any logs, error output, bugreport etc?**
OpenGLRenderer: endAllStagingAnimators on 0x55a2950170 (RippleDrawable) with handle 0x55a2661e30

after a scan i stop the qreader then a new intent.

**What is the expected behavior?**
after closing intent it should be resume the camera but it turns into black.
**Any other comments?**

**What versions of software are you using?**
+ **Device Information:** 

+ **Android Version:** 

+ **Configuration Information:** 

+ **Misc:**

**Comment by nisrulz** [comment]
Closing as issue is outdated. Please open a new issue if the issue still persists.
