### ISSUE TITLE
"Cannot find symbol" when calling QREader.getInstance().stop()

### ISSUE THREAD

**Issue by chnt-gomez** [nisrulz/qreader#7]
As it says, im calling QREader.getInstane().stop() and can't recognize the method.
public class Home extends AppCompatActivity{

    SurfaceView view;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_home);

        init();
        initQRScanner();
        startScanning();
    }

    private void init() {
        view = (SurfaceView) findViewById(R.id.sview);
        initQRScanner();
    }

    private void initQRScanner(){
        QREader.getInstance().setUpConfig(true, CameraSource.CAMERA_FACING_BACK);
    }

    private void startScanning(){
        QREader.getInstance().start(this, view, new QRDataListener() {
            @Override
            public void onDetected(String data) {
                QREader.getInstance().stop();
            }
        });

    }
    
}

**Comment by nisrulz** [comment]
@chnt-gomez please follow the updated readme instructions for v1.0.3 . I made a few changes to public methods that were exposed. 

You need to `setupConfig`, `init` and then call on `start` / `stop` and when done do `releaseAndCleanup`.
Check the code for [sample app](https://github.com/nisrulz/qreader/blob/master/app/src/main/java/github/nisrulz/projectqreader/MainActivity.java)

**Comment by chnt-gomez** [comment]
Thank you! This solution worked.
