### ISSUE TITLE
Unable to see preview

### ISSUE THREAD

**Issue by iAmAndroidDeveloper** [nisrulz/qreader#78]
@nisrulz Unable to see camera preview in following device

device name: HUAWEI MATE 30 Pro 5G
EMUI version: 11.0.0
android version: 10

Can you please check and resolved so we can upgrade and used library

**Comment by nisrulz** [comment]
This project is undergoing an update. The `develop` branch has the most updated code: https://github.com/nisrulz/qreader/tree/develop . You can checkout the module and try and validate against that.

Until the next release, I can't guarantee any stability. You will have to wait until the next stable release.

**Comment by nisrulz** [comment]
Also regarding your issue. It is a library that uses Google APIs to scan QRcode. Considering Huawei is banned from using Google APIs, I think this is why the library doesn't work for you.

My suggestion would be to use some other library that doesn't use Google Services to scan QRcodes.

**Comment by iAmAndroidDeveloper** [comment]
@nisrulz then should i used ml kit for same issue? is this work for me?

**Comment by nisrulz** [comment]
ML Kit also uses Google Services. It is part of Firebase. You need to use something that doesn't depend on Google Services.

**Comment by iAmAndroidDeveloper** [comment]
@nisrulz when I integrate ML Kit then i can see preview of camera on given device configuration
